name: rich_editor
description: WYSIWYG editor for Flutter with a rich set of supported formatting options.
version: 0.0.7
homepage: https://github.com/JideGuru/rich_editor

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ">=2.11.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.8.0
  mime: ^1.0.4
  image_picker: ^0.8.9
  flutter_widget_from_html_core: ^0.10.1
  flutter_colorpicker: ^1.0.3
  path: ^1.8.2
  xml2json: ^5.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/editor/